[package]
name = "minecraft_search_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
mongodb = "3.0.1"
rand = "0.8.5"
serde_json = "1.0.127"
tokio = { version = "1.39.3", features = ["full"] }
minecraft_protocol = { path = "minecraft_protocol" }