services:
  mse:
    build: .
    restart: unless-stopped
    volumes:
      - ./db:/app/data
    environment:
      - THREADS=900
    networks:
      - mse
    depends_on:
      - mse_mongodb

  mse_mongodb:
    image: mongo:latest
    command: ["mongod", "--quiet", "--logpath", "/dev/null", "--logappend"]
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - mse
    volumes:
      - ./data/mongo_data:/data/db
    restart: unless-stopped

networks:
  mse:
    name: mse
    driver: bridge
