services:
  mse:
    build: .
    restart: unless-stopped
    volumes:
      - ./db:/app/data
    environment:
      - THREADS=1000
      - DB=/app/data/database.db
      - UPDATE=0
      - ONLY_CRACKED=0
